/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import modelo.user;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author yefer
 */
public class Inicio extends javax.swing.JFrame {

	/**
	 * Creates new form Inicio
	 */
	public Inicio() {
		getContentPane().setBackground(new Color(123, 104, 238));
		getContentPane().setForeground(Color.WHITE);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tw Cen MT Condensed", Font.PLAIN, 17));
		codigo = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tw Cen MT Condensed", Font.BOLD, 24));
		jButton1 = new javax.swing.JButton();
		jButton1.setFont(new Font("Tw Cen MT Condensed Extra Bold", Font.PLAIN, 15));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Correo");

		jLabel2.setText("Bienvenido");

		jButton1.setText("Ingreso");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		JLabel lblNewLabel = new JLabel("Código");
		lblNewLabel.setFont(new Font("Tw Cen MT Condensed", Font.PLAIN, 17));

		correo = new JTextField();
		correo.setColumns(10);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(129)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jLabel1)
						.addComponent(lblNewLabel))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(codigo)
						.addComponent(correo, GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
						.addComponent(jButton1))
					.addContainerGap(116, Short.MAX_VALUE))
				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
					.addContainerGap(165, Short.MAX_VALUE)
					.addComponent(jLabel2)
					.addGap(162))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(24)
					.addComponent(jLabel2)
					.addGap(73)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(correo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel1))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(codigo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblNewLabel))
					.addGap(56)
					.addComponent(jButton1)
					.addContainerGap(60, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		if (codigo.getText().length() != 0) {
			JOptionPane.showMessageDialog(null, "Correo ingresado con éxito");
			modelo.user u = new modelo.user();
			u.setCodigo(codigo.getText());
			u.setCorreo(correo.getText());
			u.setCodempleado(codigo);
			u.validar(codigo);

		} else {
			JOptionPane.showMessageDialog(null, "Debe ingresar un código");
		}

	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Inicio().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField codigo;
	private JTextField correo;
}
